global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#anton_nechaev'
