version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    # build: ./ui
    image: ${GITHUB_NAME}/ui:latest
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ui:9292/healthcheck"]
      interval: 20s
      timeout: 10s
      retries: 3
    labels:
      - "autoheal=true"

  post:
    # build: ./post-py
    image: ${GITHUB_NAME}/post:latest
    networks:
      - back_net
      - front_net
  comment:
    # build: ./comment
    image: ${GITHUB_NAME}/comment:latest
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.10.1.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.10.2.0/24"
