version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - back_net
      - front_net

  fluentd:
    image: ${GITHUB_NAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - back_net

  elasticsearch:
    image: elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - back_net

  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"
    networks:
      - back_net



volumes:
  elasticsearch-data:

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.10.1.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.10.2.0/24"
