version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    # build: ./ui
    image: ${GITHUB_NAME}/ui:latest
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - front_net
  post:
    # build: ./post-py
    image: ${GITHUB_NAME}/post:latest
    networks:
      - back_net
      - front_net
  comment:
    # build: ./comment
    image: ${GITHUB_NAME}/comment:latest
    networks:
      - back_net
      - front_net

  prometheus:
    image: ${GITHUB_NAME}/prometheus
    ports:
      - '9090:9090'
    networks:
      - back_net
      - front_net
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
      - '--web.enable-admin-api'


  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    networks:
      - back_net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  mongodb-exporter:
    image:  ${GITHUB_NAME}/mongodb-exporter
    environment:
      - MONGODB_URI=mongodb://post_db:27017
    networks:
      - back_net

  blackbox-exporter:
    image: ${GITHUB_NAME}/blackbox-exporter
    command: '--config.file=/srv/blackbox.yml'
    networks:
      - back_net
      - front_net

volumes:
  post_db:
  prometheus_data:

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.10.1.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.10.2.0/24"
