{
 "title": "UI_Service_mMonitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "request latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Http Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "UI http requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{path !~\"/metrics\"}[1m])"
    }
   ]
  }
 ]
}