---
- hosts: core
  become: true
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]
    - role: preconfigure-core

- hosts: stages
  become: true
  roles:
    - role: "nickjj.docker"
      tags: ["docker"]

