version: '3'x
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${GITHUB_NAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT_EXPOSED}:${UI_PORT}/tcp
    networks:
      - front_net
  post:
    build: ./post-py
    image: ${GITHUB_NAME}/post:${POST_TAG}
    networks:
      - back_net
      - front_net
  comment:
    build: ./comment
    image: ${GITHUB_NAME}/comment:${COMMENT_TAG}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      config:
        - subnet: "10.10.1.0/24"
  front_net:
    ipam:
      config:
        - subnet: "10.10.2.0/24"
