version: '3'
services:
  post:
    volumes:
      - ./post-py:/app

  comment:
    command: ["puma", "--debug", "-w", "2"]
    volumes:
      - ./comment:/app

  ui:
    command: ["puma", "--debug", "-w", "2"]
    volumes:
      - ./ui:/app
